#!/bin/zsh


bindkey -e

bindkey "^[[A"  up-line-or-search       # cursor up
bindkey "^[[B"  down-line-or-search     # <ESC>-
bindkey '^x'    history-beginning-search-backward # alternative ways of searching the shell history

bindkey '^p'    history-search-backward # alternative ways of searching the shell history
bindkey '^n'    history-search-forward # alternative ways of searching the shell history
bindkey '^r'    history-incremental-search-backward

bindkey -s '^k' "|less\n"             # ctrl-L pipes to less
bindkey -s '^f' "ls -lh\n"



bindkey "\e[2~" quoted-insert
bindkey "\e[3~" delete-char
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey "\eOd" backward-word
bindkey "\eOc" forward-word

bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
